const String DATABASE_NAME = 'coinomy_db';

//USER
const String USER_TABLE_NAME = 'user';
const String USER_COLUMN_ID = 'userID';
const String USER_COLUMN_NAME = 'name';
const String USER_COLUMN_EMAIL = 'email';
const String USER_COLUMN_PASSWORD = 'password';

const String CREATE_USER_TABLE_SCRIPT = '''
  CREATE TABLE $USER_TABLE_NAME(
    $USER_COLUMN_ID INTEGER PRIMARY KEY,
    $USER_COLUMN_NAME TEXT,
    $USER_COLUMN_EMAIL TEXT,
    $USER_COLUMN_PASSWORD TEXT,
  )
''';

//TRANSACTION
const String TRANSACTION_TABLE_NAME = 'transaction';
const String TRANSACTION_COLUMN_ID = 'transactionID';
const String TRANSACTION_COLUMN_DESCRIPTION = 'description';
const String TRANSACTION_COLUMN_TYPE = 'type';
const String TRANSACTION_COLUMN_VALUE = 'value';
const String TRANSACTION_COLUMN_CATEGORY = 'category';

const String CREATE_TRANSACTION_TABLE_SCRIPT = '''
  CREATE TABLE $TRANSACTION_TABLE_NAME(
    $TRANSACTION_COLUMN_ID INTEGER PRIMARY KEY,
    $TRANSACTION_COLUMN_DESCRIPTION TEXT,
    $TRANSACTION_COLUMN_TYPE TEXT,
    $TRANSACTION_COLUMN_VALUE DECIMAL,
    $TRANSACTION_COLUMN_CATEGORY TEXT
  )
''';
